mqtt:
  host: '{FRIGATE_MQTT_HOST}'
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  ov_0:
    type: openvino
    device: GPU

# Optional: model modifications
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  attributes_map:
    person:
      - face

# Optional: Audio Events Configuration
# NOTE: Can be overridden at the camera level
audio:
  enabled: true
  max_not_heard: 30
  min_volume: 1000
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    speech:
      threshold: 0.8

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  alerts:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 30
      mode: motion
  detections:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 30
      mode: motion

# Optional: Configuration for the jpg snapshots written to the clips directory for each tracked object
# NOTE: Can be overridden at the camera level
snapshots:
  enabled: true
  clean_copy: true
  retain:
    default: 30
    objects:
      person: 15
  quality: 80

face_recognition:
  enabled: true
  model_size: small

# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args:
    - -hwaccel
    - vaapi
    - -rtsp_transport
    - tcp

# Optional: Restream configuration
# Uses https://github.com/AlexxIT/go2rtc (v1.9.10)
# NOTE: The default go2rtc API port (1984) must be used,
#       changing this port for the integrated go2rtc instance is not supported.
go2rtc:
  streams:
    puerta_cam:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_IP_CAMERA_PUERTA}:554/stream1#video=copy#audio=aac
    puerta_cam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_IP_CAMERA_PUERTA}:554/stream2
    patio_cam:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_IP_CAMERA_PATIO}:554/stream1#video=copy#audio=aac
    patio_cam_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_IP_CAMERA_PATIO}:554/stream2

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.75

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tr
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%d/%m/%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: solid

# Required
cameras:
  # You can create multiple cameras, by adding additional blocks after this camera
  # customise the camera name (camera_one) as you wish.
  puerta:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/puerta_cam
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect
    live:
      streams:
        Main Stream: puerta_cam
        Sub Stream: puerta_cam_sub
    detect:
      width: 2304
      height: 1296
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
    zones:
      frente_puerta:
        coordinates: 0.237,0.265,0.824,0.255,0.813,0.71,0.492,0.734,0.272,0.74
        loitering_time: 10
        objects: person
        inertia: 3
      frente_interior:
        coordinates: 0.282,0.99,0.883,0.994,0.817,0.724,0.093,0.751,0.004,0.978
        loitering_time: 0
        objects: person
        inertia: 3
    motion:
      mask:
        - 0,0.05,0.36,0.052,0.362,0,0,0
        - 0.865,0,1,0,1,0.559,0.972,0.555,0.968,0.391,0.934,0.366,0.912,0.294,0.878,0.174
    objects:
      track:
        - person
        - bicycle
        - motorcycle
      filters:
        person:
          threshold: 0.7
          min_area: 1800
    review:
      alerts:
        required_zones:
          - frente_puerta
          - frente_interior
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio_cam
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/patio_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    live:
      streams:
        Main Stream: patio_cam
        Sub Stream: patio_cam_sub
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
    motion:
      mask: 0.488,0.302,0.22,0.28,0,0.09,0,0,0.579,0
      threshold: 30
      contour_area: 11
      improve_contrast: true
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.7
          min_area: 1800
    zones: {}

detect:
  enabled: true

version: 0.16-0
semantic_search:
  enabled: true
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
