services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 1883:1883
      - 9001:9001

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - ./frigate/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    restart: unless-stopped
    environment:
      FRIGATE_MQTT_USER: ${FRIGATE_MQTT_USER}
      FRIGATE_MQTT_PASSWORD: ${FRIGATE_MQTT_PASSWORD}
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
      FRIGATE_RTSP_USER: ${FRIGATE_RTSP_USER}
      FRIGATE_TAPO_TOKEN: ${FRIGATE_TAPO_TOKEN}
      FRIGATE_IP_CAMERA_PUERTA: ${FRIGATE_IP_CAMERA_PUERTA}
      FRIGATE_IP_CAMERA_PATIO: ${FRIGATE_IP_CAMERA_PATIO}
      HOST_IP: ${HOST_IP}
      LIBVA_DRIVER_NAME: i965
    ports:
      - 5000:5000
      - 8544:8544
      - 8555:8555/tcp
      - 8555:8555/udp
    privileged: true
    shm_size: '256mb'
    devices:
      - /dev/dri/renderD128
    depends_on:
      - mosquitto
  
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    depends_on:
      - mosquitto
      - frigate
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./ha/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host