- id: '1772824721404'
  alias: NotificacionPuerta
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.frente_puerta_person_occupancy
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - device_id: 38eeba5e8bb9577e19431e1b47a7745d
    domain: mobile_app
    type: notify
    message: Persona detectada
    data:
      image: /api/image_proxy/image.puerta_person
      channel: Timbre
    title: Aviso Puerta
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  mode: single
- id: '1776448782214'
  alias: NotificacionPuertaInterior
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.frente_interior_person_occupancy
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - device_id: 38eeba5e8bb9577e19431e1b47a7745d
    domain: mobile_app
    type: notify
    message: Persona detectada dentro
    data:
      image: /api/image_proxy/image.puerta_person
      channel: Timbre
    title: Aviso Puerta Interior
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  mode: single
